### ISSUE TITLE
Push Mod Versions (files and data)

### ISSUE THREAD

**Issue by XCompWiz** [PackAssembler/PackAssembler#25]
If you can give us a system to push versions of the mod to the system, rather than needing to pull them from the web interface, we can push versions of a mod as they are built... (I in particular would do this for Mystcraft, you'd be one of the first to get an update).

This can range from ftp transfer with json files for entry data to some kind of remote upload.  Regardless, I'd want something I could automate.

**Comment by stephenmac7** [comment]
This already exists, though it's not documented correctly. You can submit a GET or POST (preferable) request to http://mml.stephenmac.com/mods/{modid}/versions/quickadd with these parameters:
- username: Your username on PackAssembler
- password: Your password
- version: The new version number
- mc: Target minecraft version (ask if you want to be able to specify mc_max and mc_min)
- url: A URL to the mod file, so that it can be downloaded, hashed, and stored
